name: CI/CD Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependency
        run: npm ci

      - name: Jalankan unit test
        run: npm test

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Ambil kode repository
        uses: actions/checkout@v4

      - name: Konfigurasi GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload file website
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4